/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BackEnd.DataClass;
import Controller.BackEnd.TeacherClass;
import Controller.BackEnd.UsersClass;
import Controller.BackEnd.timeTableClass;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import Controller.BackEnd.StudentClass;
import javax.swing.table.DefaultTableModel;
import View.Game.Game;

/**
 *
 * @author Abdullah123
 */
@SuppressWarnings("serial")
public class Teacher extends javax.swing.JFrame {
    private String questionTypeString = "MCQ";
    private ArrayList<Question>questionsArrayList=new ArrayList<>();
    private JRadioButton[] selectionOptions=new JRadioButton[4];
    private int noOfQuestions = 0 ;
    private UsersClass User ;
    private DataClass data ;
    private String user ;
    private int mouseX;
    private int mouseY;
    /**
     * Creates new form Teacher
     */
    public Teacher(UsersClass User, DataClass data , String user) {
        this.User=User;
        this.data=data;
        this.user=user;
        LookAndFeel.lookAndFeel("Metal");
        initComponents();
        this.setVisible(true);  
        selectionOptions[0]=a;
        selectionOptions[1]=b;
        selectionOptions[2]=c;
        selectionOptions[3]=d;
        a.setVisible(true);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        paperLayerd.setVisible(false);
        initializeDashBoard();
        intitialize();
        setVisible();
        DashBoard.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackPanel = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JLayeredPane();
        WelcomeMessage = new javax.swing.JLabel();
        dashBoard = new javax.swing.JButton();
        markStudentAttendance = new javax.swing.JButton();
        markStudentMarks = new javax.swing.JButton();
        createAnExam = new javax.swing.JButton();
        entertainment = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        LeftBackground = new javax.swing.JLabel();
        RightPanel = new javax.swing.JLayeredPane();
        EntertainmentPanel = new javax.swing.JPanel();
        dashBoard1 = new javax.swing.JButton();
        teacher1 = new javax.swing.JButton();
        RightBackground10 = new javax.swing.JLabel();
        examPanel = new javax.swing.JPanel();
        option = new javax.swing.JLabel();
        options = new javax.swing.JComboBox<>();
        createPaper = new javax.swing.JButton();
        nextQuestion = new javax.swing.JButton();
        previousQuestion = new javax.swing.JButton();
        marks = new javax.swing.JLabel();
        marksField = new javax.swing.JTextField();
        question = new javax.swing.JLabel();
        questionType = new javax.swing.JLabel();
        questions = new javax.swing.JTextField();
        questionsType = new javax.swing.JComboBox<>();
        a = new javax.swing.JRadioButton();
        b = new javax.swing.JRadioButton();
        c = new javax.swing.JRadioButton();
        d = new javax.swing.JRadioButton();
        RightBackground5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentAttendancePanel = new javax.swing.JPanel();
        todaysAttendance1 = new javax.swing.JLabel();
        todaysAttendance6 = new javax.swing.JLabel();
        subject = new javax.swing.JComboBox<>();
        sections = new javax.swing.JComboBox<>();
        todaysAttendance2 = new javax.swing.JLabel();
        previousDates1 = new javax.swing.JComboBox<>();
        todaysAttendance3 = new javax.swing.JLabel();
        semesters = new javax.swing.JComboBox<>();
        attendanceScrollPane = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        RightBackground4 = new javax.swing.JLabel();
        setAttendance = new javax.swing.JButton();
        studentsMarks = new javax.swing.JPanel();
        todaysAttendance7 = new javax.swing.JLabel();
        subject1 = new javax.swing.JComboBox<>();
        todaysAttendance4 = new javax.swing.JLabel();
        sections1 = new javax.swing.JComboBox<>();
        todaysAttendance5 = new javax.swing.JLabel();
        semester1 = new javax.swing.JComboBox<>();
        marksPanelScroll = new javax.swing.JScrollPane();
        marksPanel = new javax.swing.JTable();
        doneMarks = new javax.swing.JButton();
        RightBackground9 = new javax.swing.JLabel();
        paperLayerd = new javax.swing.JLayeredPane();
        paperQuestionPanel = new javax.swing.JPanel();
        questionNo = new javax.swing.JLabel();
        a1 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JRadioButton();
        d1 = new javax.swing.JRadioButton();
        c1 = new javax.swing.JRadioButton();
        examQuestionScroll = new javax.swing.JScrollPane();
        examQuestionField = new javax.swing.JTextArea();
        answerScrollPanel = new javax.swing.JScrollPane();
        studentPanel = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        questionMarks = new javax.swing.JLabel();
        nextQuestion1 = new javax.swing.JButton();
        previousQuestion1 = new javax.swing.JButton();
        RightBackground6 = new javax.swing.JLabel();
        DashBoard = new javax.swing.JPanel();
        attendancePercentageAnswer = new javax.swing.JTextField();
        attendancePercentage = new javax.swing.JLabel();
        attendanceAnswer = new javax.swing.JTextField();
        previousDates = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        absent = new javax.swing.JRadioButton();
        present = new javax.swing.JRadioButton();
        todaysAttendance = new javax.swing.JLabel();
        RightBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeMessage.setBackground(new java.awt.Color(0, 0, 204));
        WelcomeMessage.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        WelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeMessage.setText("WELCOME ");
        WelcomeMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        WelcomeMessage.setOpaque(true);
        WelcomeMessage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                WelcomeMessageMouseDragged(evt);
            }
        });
        WelcomeMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WelcomeMessageMousePressed(evt);
            }
        });
        LeftPanel.add(WelcomeMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 63));

        dashBoard.setBackground(new java.awt.Color(0, 0, 0));
        dashBoard.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        dashBoard.setForeground(new java.awt.Color(51, 255, 51));
        dashBoard.setText("DASHBOARD ");
        dashBoard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        dashBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashBoardMouseClicked(evt);
            }
        });
        LeftPanel.add(dashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, -1));

        markStudentAttendance.setBackground(new java.awt.Color(0, 0, 0));
        markStudentAttendance.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        markStudentAttendance.setForeground(new java.awt.Color(51, 255, 51));
        markStudentAttendance.setText("MARK STUDENTS ATTENDANCE ");
        markStudentAttendance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        markStudentAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        markStudentAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                markStudentAttendanceMouseClicked(evt);
            }
        });
        markStudentAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markStudentAttendanceActionPerformed(evt);
            }
        });
        LeftPanel.add(markStudentAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 276, 250, -1));

        markStudentMarks.setBackground(new java.awt.Color(0, 0, 0));
        markStudentMarks.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        markStudentMarks.setForeground(new java.awt.Color(51, 255, 51));
        markStudentMarks.setText("STUDENT  MARKS ");
        markStudentMarks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        markStudentMarks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        markStudentMarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                markStudentMarksMouseClicked(evt);
            }
        });
        LeftPanel.add(markStudentMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 250, -1));

        createAnExam.setBackground(new java.awt.Color(0, 0, 0));
        createAnExam.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        createAnExam.setForeground(new java.awt.Color(51, 255, 51));
        createAnExam.setText("CREATE AN EXAM ");
        createAnExam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        createAnExam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAnExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAnExamActionPerformed(evt);
            }
        });
        LeftPanel.add(createAnExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 344, 250, -1));

        entertainment.setBackground(new java.awt.Color(0, 0, 0));
        entertainment.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        entertainment.setForeground(new java.awt.Color(51, 255, 51));
        entertainment.setText("ENTERTAINMENT ");
        entertainment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        entertainment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entertainment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entertainmentActionPerformed(evt);
            }
        });
        LeftPanel.add(entertainment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 378, 250, -1));

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        logout.setForeground(new java.awt.Color(51, 255, 51));
        logout.setText("LOGOUT ");
        logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        LeftPanel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 250, -1));

        LeftBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Menu Background.jpg"))); // NOI18N
        LeftBackground.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));
        LeftPanel.add(LeftBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 270, 470));

        BackPanel.add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 530));

        RightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EntertainmentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashBoard1.setBackground(new java.awt.Color(0, 0, 0));
        dashBoard1.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        dashBoard1.setForeground(new java.awt.Color(51, 255, 51));
        dashBoard1.setText("GAME ");
        dashBoard1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        dashBoard1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashBoard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashBoard1MouseClicked(evt);
            }
        });
        dashBoard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashBoard1ActionPerformed(evt);
            }
        });
        EntertainmentPanel.add(dashBoard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 250, -1));

        teacher1.setBackground(new java.awt.Color(0, 0, 0));
        teacher1.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        teacher1.setForeground(new java.awt.Color(51, 255, 51));
        teacher1.setText("MUSIC PLAYER ");
        teacher1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        teacher1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teacher1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacher1MouseClicked(evt);
            }
        });
        teacher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher1ActionPerformed(evt);
            }
        });
        EntertainmentPanel.add(teacher1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 250, -1));

        RightBackground10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightBackground10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Right panel background.jpg"))); // NOI18N
        RightBackground10.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));
        EntertainmentPanel.add(RightBackground10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 800, 530));

        RightPanel.add(EntertainmentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 530));

        examPanel.setBackground(new java.awt.Color(0, 0, 204));
        examPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        option.setBackground(new java.awt.Color(0, 51, 255));
        option.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        option.setForeground(new java.awt.Color(0, 255, 51));
        option.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        option.setText("OPTIONS  ");
        option.setOpaque(true);
        examPanel.add(option, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 140, 20));

        options.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        options.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });
        examPanel.add(options, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 130, 20));

        createPaper.setBackground(new java.awt.Color(0, 0, 0));
        createPaper.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        createPaper.setForeground(new java.awt.Color(51, 255, 51));
        createPaper.setText("GENERATE PAPER");
        createPaper.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        createPaper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createPaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createPaperMouseClicked(evt);
            }
        });
        createPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPaperActionPerformed(evt);
            }
        });
        examPanel.add(createPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 160, -1));

        nextQuestion.setBackground(new java.awt.Color(0, 0, 0));
        nextQuestion.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        nextQuestion.setForeground(new java.awt.Color(51, 255, 51));
        nextQuestion.setText("NEXT QUESTION");
        nextQuestion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        nextQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextQuestionMouseClicked(evt);
            }
        });
        nextQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQuestionActionPerformed(evt);
            }
        });
        examPanel.add(nextQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 150, -1));

        previousQuestion.setBackground(new java.awt.Color(0, 0, 0));
        previousQuestion.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        previousQuestion.setForeground(new java.awt.Color(51, 255, 51));
        previousQuestion.setText("PREVIOUS QUESTION");
        previousQuestion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        previousQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousQuestionMouseClicked(evt);
            }
        });
        previousQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousQuestionActionPerformed(evt);
            }
        });
        examPanel.add(previousQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 160, -1));

        marks.setBackground(new java.awt.Color(0, 51, 255));
        marks.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        marks.setForeground(new java.awt.Color(0, 255, 51));
        marks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marks.setText("QUESTION's MARKS ");
        marks.setOpaque(true);
        examPanel.add(marks, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 140, 20));
        examPanel.add(marksField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 130, -1));

        question.setBackground(new java.awt.Color(0, 51, 255));
        question.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        question.setForeground(new java.awt.Color(0, 255, 51));
        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question.setText("QUESTION ");
        question.setOpaque(true);
        examPanel.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, 20));

        questionType.setBackground(new java.awt.Color(0, 51, 255));
        questionType.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        questionType.setForeground(new java.awt.Color(0, 255, 51));
        questionType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionType.setText("QUESTION TYPE");
        questionType.setOpaque(true);
        examPanel.add(questionType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, 20));

        questions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionsActionPerformed(evt);
            }
        });
        examPanel.add(questions, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 280, -1));

        questionsType.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        questionsType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MCQ's ", "QUESTION " }));
        questionsType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        questionsType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                questionsTypeMouseClicked(evt);
            }
        });
        questionsType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionsTypeActionPerformed(evt);
            }
        });
        examPanel.add(questionsType, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 140, 20));

        a.setBackground(new java.awt.Color(255, 255, 255));
        a.setText("a)");
        a.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        examPanel.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 90, -1));

        b.setText("b)");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        examPanel.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 90, -1));

        c.setText("c)");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        examPanel.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 90, -1));

        d.setText("d)");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        examPanel.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 90, -1));

        RightBackground5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightBackground5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Right panel background.jpg"))); // NOI18N
        RightBackground5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));
        examPanel.add(RightBackground5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 800, 530));

        RightPanel.add(examPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        StudentAttendancePanel.setBackground(new java.awt.Color(0, 0, 204));
        StudentAttendancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        todaysAttendance1.setBackground(new java.awt.Color(0, 51, 255));
        todaysAttendance1.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        todaysAttendance1.setForeground(new java.awt.Color(0, 255, 51));
        todaysAttendance1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todaysAttendance1.setText("DATE");
        todaysAttendance1.setOpaque(true);
        StudentAttendancePanel.add(todaysAttendance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 80, -1));

        todaysAttendance6.setBackground(new java.awt.Color(0, 51, 255));
        todaysAttendance6.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        todaysAttendance6.setForeground(new java.awt.Color(0, 255, 51));
        todaysAttendance6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todaysAttendance6.setText("SUBJECT");
        todaysAttendance6.setOpaque(true);
        StudentAttendancePanel.add(todaysAttendance6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, 20));

        subject.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        subject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        StudentAttendancePanel.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 130, 20));

        sections.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        sections.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionsActionPerformed(evt);
            }
        });
        StudentAttendancePanel.add(sections, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 140, 20));

        todaysAttendance2.setBackground(new java.awt.Color(0, 51, 255));
        todaysAttendance2.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        todaysAttendance2.setForeground(new java.awt.Color(0, 255, 51));
        todaysAttendance2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todaysAttendance2.setText("SECTION ");
        todaysAttendance2.setOpaque(true);
        StudentAttendancePanel.add(todaysAttendance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 80, 20));

        previousDates1.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        previousDates1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentAttendancePanel.add(previousDates1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 140, 20));

        todaysAttendance3.setBackground(new java.awt.Color(0, 51, 255));
        todaysAttendance3.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        todaysAttendance3.setForeground(new java.awt.Color(0, 255, 51));
        todaysAttendance3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todaysAttendance3.setText("SEMESTER");
        todaysAttendance3.setOpaque(true);
        StudentAttendancePanel.add(todaysAttendance3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 20));

        semesters.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        semesters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        semesters.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semesters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semestersActionPerformed(evt);
            }
        });
        StudentAttendancePanel.add(semesters, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 130, 20));

        attendanceScrollPane.setBackground(new java.awt.Color(0, 0, 0));
        attendanceScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        attendanceScrollPane.setForeground(new java.awt.Color(255, 255, 255));
        attendanceScrollPane.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        attendanceTable.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "NAME", "ROLL NUMBER", "ATTENDANCE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        attendanceTable.setGridColor(new java.awt.Color(0, 0, 0));
        attendanceScrollPane.setViewportView(attendanceTable);

        StudentAttendancePanel.add(attendanceScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 490, 390));

        RightBackground4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightBackground4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Right panel background.jpg"))); // NOI18N
        RightBackground4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));
        StudentAttendancePanel.add(RightBackground4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 800, 530));

        setAttendance.setBackground(new java.awt.Color(0, 0, 0));
        setAttendance.setForeground(new java.awt.Color(0, 255, 0));
        setAttendance.setText("OK");
        setAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAttendanceActionPerformed(evt);
            }
        });
        StudentAttendancePanel.add(setAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 530, 100, -1));

        jScrollPane1.setViewportView(StudentAttendancePanel);

        RightPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 530));

        studentsMarks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        todaysAttendance7.setBackground(new java.awt.Color(0, 51, 255));
        todaysAttendance7.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        todaysAttendance7.setForeground(new java.awt.Color(0, 255, 51));
        todaysAttendance7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todaysAttendance7.setText("SUBJECT");
        todaysAttendance7.setOpaque(true);
        studentsMarks.add(todaysAttendance7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 80, 20));

        subject1.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        subject1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject1ActionPerformed(evt);
            }
        });
        studentsMarks.add(subject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 130, 20));

        todaysAttendance4.setBackground(new java.awt.Color(0, 51, 255));
        todaysAttendance4.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        todaysAttendance4.setForeground(new java.awt.Color(0, 255, 51));
        todaysAttendance4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todaysAttendance4.setText("SECTION ");
        todaysAttendance4.setOpaque(true);
        studentsMarks.add(todaysAttendance4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 20));

        sections1.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        sections1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sections1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sections1ActionPerformed(evt);
            }
        });
        studentsMarks.add(sections1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, 20));

        todaysAttendance5.setBackground(new java.awt.Color(0, 51, 255));
        todaysAttendance5.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        todaysAttendance5.setForeground(new java.awt.Color(0, 255, 51));
        todaysAttendance5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todaysAttendance5.setText("SEMESTER");
        todaysAttendance5.setOpaque(true);
        studentsMarks.add(todaysAttendance5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 90, 20));

        semester1.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        semester1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semester1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester1ActionPerformed(evt);
            }
        });
        studentsMarks.add(semester1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 130, 20));

        marksPanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT NAME", "ROLL NO.", "MARKS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        marksPanelScroll.setViewportView(marksPanel);

        studentsMarks.add(marksPanelScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 510, 380));

        doneMarks.setText("DONE");
        doneMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneMarksActionPerformed(evt);
            }
        });
        studentsMarks.add(doneMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 80, -1));

        RightBackground9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightBackground9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Right panel background.jpg"))); // NOI18N
        RightBackground9.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));
        studentsMarks.add(RightBackground9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 800, 530));

        RightPanel.add(studentsMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 530));

        paperLayerd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paperQuestionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 5, true));
        paperQuestionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questionNo.setText("Question no :");
        paperQuestionPanel.add(questionNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        a1.setBackground(new java.awt.Color(204, 204, 204));
        a1.setText("a)");
        a1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        paperQuestionPanel.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 180, 30));

        b1.setText("b)");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        paperQuestionPanel.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 220, 30));

        d1.setText("d)");
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        paperQuestionPanel.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 210, 30));

        c1.setBackground(new java.awt.Color(204, 204, 204));
        c1.setText("c)");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        paperQuestionPanel.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 220, 30));

        examQuestionField.setEditable(false);
        examQuestionField.setColumns(20);
        examQuestionField.setRows(5);
        examQuestionScroll.setViewportView(examQuestionField);

        paperQuestionPanel.add(examQuestionScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 390, 30));

        studentPanel.setColumns(20);
        studentPanel.setRows(5);
        answerScrollPanel.setViewportView(studentPanel);

        paperQuestionPanel.add(answerScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 390, 180));

        jLabel2.setText("Answer :");
        paperQuestionPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, -1));

        questionMarks.setText("Marks :");
        paperQuestionPanel.add(questionMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        paperLayerd.add(paperQuestionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 510, 250));

        nextQuestion1.setBackground(new java.awt.Color(0, 0, 0));
        nextQuestion1.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        nextQuestion1.setForeground(new java.awt.Color(51, 255, 51));
        nextQuestion1.setText("NEXT QUESTION");
        nextQuestion1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        nextQuestion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextQuestion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextQuestion1MouseClicked(evt);
            }
        });
        nextQuestion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQuestion1ActionPerformed(evt);
            }
        });
        paperLayerd.add(nextQuestion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 150, -1));

        previousQuestion1.setBackground(new java.awt.Color(0, 0, 0));
        previousQuestion1.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        previousQuestion1.setForeground(new java.awt.Color(51, 255, 51));
        previousQuestion1.setText("PREVIOUS QUESTION");
        previousQuestion1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        previousQuestion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousQuestion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousQuestion1MouseClicked(evt);
            }
        });
        previousQuestion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousQuestion1ActionPerformed(evt);
            }
        });
        paperLayerd.add(previousQuestion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 160, -1));

        RightBackground6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightBackground6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Right panel background.jpg"))); // NOI18N
        RightBackground6.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));
        paperLayerd.add(RightBackground6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 800, 530));

        RightPanel.add(paperLayerd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        DashBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendancePercentageAnswer.setEditable(false);
        attendancePercentageAnswer.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        attendancePercentageAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendancePercentageAnswerActionPerformed(evt);
            }
        });
        DashBoard.add(attendancePercentageAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 310, 30));

        attendancePercentage.setBackground(new java.awt.Color(51, 51, 255));
        attendancePercentage.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        attendancePercentage.setForeground(new java.awt.Color(102, 255, 51));
        attendancePercentage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendancePercentage.setText("ATTENDANCE PERCENTAGE ");
        attendancePercentage.setOpaque(true);
        DashBoard.add(attendancePercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 310, 50));

        attendanceAnswer.setEditable(false);
        attendanceAnswer.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        DashBoard.add(attendanceAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 310, 30));

        previousDates.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        previousDates.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousDatesActionPerformed(evt);
            }
        });
        DashBoard.add(previousDates, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 310, 30));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PREVIOUS ATTENDANCE ");
        jLabel1.setOpaque(true);
        DashBoard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 201, 310, 50));

        absent.setFont(new java.awt.Font("Segoe Print", 3, 11)); // NOI18N
        absent.setText("ABSENT ");
        absent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        absent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        absent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absentMouseClicked(evt);
            }
        });
        absent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absentActionPerformed(evt);
            }
        });
        DashBoard.add(absent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 160, 30));

        present.setFont(new java.awt.Font("Segoe Print", 3, 11)); // NOI18N
        present.setText("PRESENT ");
        present.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        present.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        present.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                presentMouseClicked(evt);
            }
        });
        present.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentActionPerformed(evt);
            }
        });
        DashBoard.add(present, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 150, 30));

        todaysAttendance.setBackground(new java.awt.Color(0, 51, 255));
        todaysAttendance.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        todaysAttendance.setForeground(new java.awt.Color(0, 255, 51));
        todaysAttendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todaysAttendance.setText("TODAY'S ATTENDANCE ");
        todaysAttendance.setOpaque(true);
        DashBoard.add(todaysAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 310, 50));

        RightBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Right panel background.jpg"))); // NOI18N
        RightBackground.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));
        DashBoard.add(RightBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 800, 530));

        RightPanel.add(DashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 530));

        BackPanel.add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 530, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashBoardMouseClicked
        setVisible();
        DashBoard.setVisible(true);
    }//GEN-LAST:event_dashBoardMouseClicked

    private void markStudentAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markStudentAttendanceMouseClicked
        setVisible();
        StudentAttendancePanel.setVisible(true);
    }//GEN-LAST:event_markStudentAttendanceMouseClicked

    private void markStudentMarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markStudentMarksMouseClicked
        setVisible();
        studentsMarks.setVisible(true);
    }//GEN-LAST:event_markStudentMarksMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.dispose();
        new Signin(User, data);
    }//GEN-LAST:event_logoutActionPerformed

    private void entertainmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entertainmentActionPerformed
        setVisible();
        EntertainmentPanel.setVisible(true);
    }//GEN-LAST:event_entertainmentActionPerformed

    private void dashBoard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashBoard1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashBoard1MouseClicked

    private void dashBoard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashBoard1ActionPerformed
        new Game();
    }//GEN-LAST:event_dashBoard1ActionPerformed

    private void teacher1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher1MouseClicked

    private void attendancePercentageAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendancePercentageAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendancePercentageAnswerActionPerformed

    private void absentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absentMouseClicked
        if(present.isSelected())
        present.setSelected(false);
    }//GEN-LAST:event_absentMouseClicked

    private void presentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_presentMouseClicked
        if(absent.isSelected())
        absent.setSelected(false);
    }//GEN-LAST:event_presentMouseClicked

    private void nextQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextQuestionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nextQuestionMouseClicked

    private void previousQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousQuestionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_previousQuestionMouseClicked

    private void previousQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousQuestionActionPerformed
        if(questionsArrayList.size()!=0){
            --noOfQuestions;
            if(noOfQuestions>=0){
            Question question=questionsArrayList.get(noOfQuestions);
            questionsType.setSelectedItem(question.getQuestionType());
            questions.setText(question.getQuestion());
            marksField.setText(Integer.toString(question.getQuestionMarks()));
            options.setSelectedItem(question.getOptions());
            for(int i = 0 ; i < question.getOptions();i++){
                selectionOptions[i].setVisible(true);
                if(selectionOptions[i].getText().equals(question.getOption().getText()))
                    selectionOptions[i].setSelected(true);
            }
            }
            else noOfQuestions++;
        }
        System.out.println(paperLayerd.getBounds());
        paperLayerd.setBounds(0, 0, paperLayerd.getWidth(), paperLayerd.getHeight()+248);
    }//GEN-LAST:event_previousQuestionActionPerformed

    private void createPaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createPaperMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createPaperMouseClicked

    private void createPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPaperActionPerformed

    private void questionsTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_questionsTypeMouseClicked
        questionTypeString=(String)questionsType.getSelectedItem();
        if (questionTypeString.equals("QUESTION")){
            option.setVisible(false);
            options.setVisible(false);
            a.setVisible(false);
            b.setVisible(false);
            c.setVisible(false);
            d.setVisible(false);
        }
        else{
            option.setVisible(true);
            options.setVisible(true);
            a.setVisible(true);
            b.setVisible(true);
            c.setVisible(true);
            d.setVisible(true);
        }
        System.out.println(questionTypeString);
    }//GEN-LAST:event_questionsTypeMouseClicked

    private void questionsTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionsTypeActionPerformed
        questionTypeString=(String)questionsType.getSelectedItem();
        if (questionTypeString.equals("QUESTION")){
            option.setVisible(false);
            options.setVisible(false);
            a.setVisible(false);
            b.setVisible(false);
            c.setVisible(false);
            d.setVisible(false);
        }
        else{
            option.setVisible(true);
            options.setVisible(true);
            a.setVisible(true);
            b.setVisible(true);
            c.setVisible(true);
            d.setVisible(true);
        }
    }//GEN-LAST:event_questionsTypeActionPerformed

    private void optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsActionPerformed
        if (options.getSelectedItem().equals("1")){
            a.setVisible(true);
            b.setVisible(false);
            c.setVisible(false);
            d.setVisible(false);
        }
        else if (options.getSelectedItem().equals("2")){
            a.setVisible(true);
            b.setVisible(true);
            c.setVisible(false);
            d.setVisible(false);
        }
        else if (options.getSelectedItem().equals("3")){
            a.setVisible(true);
            b.setVisible(true);
            c.setVisible(true);
            d.setVisible(false);
        }
        else if (options.getSelectedItem().equals("4")){
            a.setVisible(true);
            b.setVisible(true);
            c.setVisible(true);
            d.setVisible(true);
        }
    }//GEN-LAST:event_optionsActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        b.setSelected(false);
        c.setSelected(false);
        d.setSelected(false);
        a.setText("a) " + JOptionPane.showInputDialog("Please enter option"));
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        a.setSelected(false);
        c.setSelected(false);
        d.setSelected(false);
        b.setText("a) " + JOptionPane.showInputDialog("Please enter option"));
    }//GEN-LAST:event_bActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        b.setSelected(false);
        a.setSelected(false);
        d.setSelected(false);
        c.setText("a) " + JOptionPane.showInputDialog("Please enter option"));
    }//GEN-LAST:event_cActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        b.setSelected(false);
        a.setSelected(false);
        c.setSelected(false);
        d.setText("a) " + JOptionPane.showInputDialog("Please enter option"));
    }//GEN-LAST:event_dActionPerformed

    private void nextQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextQuestionActionPerformed
        if(!marksField.getText().isBlank()&&!marksField.getText().isBlank()){
        int noOfValues = Integer.parseInt((String)options.getSelectedItem());
        int marksOfQuestion=0;
        try{
            marksOfQuestion=Integer.parseInt(marksField.getText());
        }catch(Exception e){
            marksOfQuestion=1;
        }
        JRadioButton selectedButton=null;
        for(JRadioButton button : selectionOptions){
            if(button.isSelected()){
                selectedButton=button;
                break;
            }
        }
        if(selectedButton!=null){
        questionsArrayList.add(noOfQuestions,questionsType.getSelectedItem().toString().equals("MCQ's ")?new Question(questionTypeString, questions.getText(),marksOfQuestion, noOfValues,selectedButton ):new Question(questionTypeString, questions.getText(),marksOfQuestion) );
        questions.setText("");
        marksField.setText("");
        options.setSelectedIndex(0);
        questionsType.setSelectedIndex(0);
        String []options={"a)","b)","c)","d)"};
        for(int i = 0 ; i < noOfValues;i++){
            selectionOptions[i].setText(options[i]);
            selectionOptions[i].setSelected(false);
        }
        noOfQuestions++;
        selectionOptions[0].setVisible(true);
        selectionOptions[1].setVisible(false);
        selectionOptions[2].setVisible(false);
        selectionOptions[3].setVisible(false);
        }
        else 
            JOptionPane.showMessageDialog(this, "Please select the right option!");
        }
        else
            JOptionPane.showMessageDialog(this, "Please fill all the fields!");
    }//GEN-LAST:event_nextQuestionActionPerformed

    private void questionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionsActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void nextQuestion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextQuestion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nextQuestion1MouseClicked

    private void nextQuestion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextQuestion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextQuestion1ActionPerformed

    private void previousQuestion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousQuestion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_previousQuestion1MouseClicked

    private void previousQuestion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousQuestion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousQuestion1ActionPerformed

    private void presentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentActionPerformed
        if(absent.isSelected())
            absent.setSelected(false);
        present.setSelected(true);
        User.markAttendance(User.getUsers().get(user).getName(),true);
        boolean contains = false;
        for(int i = 0 ; i < previousDates.getItemCount() ; i++ ){
            if(previousDates.getItemAt(i).toString().equals(getDateFormat(LocalDate.now()))){
                contains=true;
                break;
            }
        }
        if(!contains||previousDates.getItemCount()==0){
            previousDates.insertItemAt(getDateFormat(LocalDate.now()),0);
        }
        previousDates.setSelectedIndex(0);
    }//GEN-LAST:event_presentActionPerformed

    private void absentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absentActionPerformed
        if(present.isSelected())
            present.setSelected(false);
        absent.setSelected(true);
        User.markAttendance(User.getUsers().get(user).getName(),false);
        boolean contains = false;
        for(int i = 0 ; i < previousDates.getItemCount() ; i++ ){
            if(previousDates.getItemAt(i).toString().equals(getDateFormat(LocalDate.now()))){
                contains=true;
                break;
            }
        }
        if(!contains||previousDates.getItemCount()==0){
            previousDates.insertItemAt(getDateFormat(LocalDate.now()),0);
        }
        previousDates.setSelectedIndex(0);
    }//GEN-LAST:event_absentActionPerformed

    private void previousDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousDatesActionPerformed
        for(LocalDate localDate:User.getAttendance().get(User.getUser(user).getName()).keySet()){
            if(getDateFormat(localDate).equals(previousDates.getSelectedItem())){
                attendanceAnswer.setText(User.getAttendance().get(User.getUser(user).getName()).get(localDate)?"Present":"Absent");
                User.calculateAttendancePercentage();
                attendancePercentageAnswer.setText(User.getAttendancePercentage(User.getUsers().get(user).getName()));
            }
        }
    }//GEN-LAST:event_previousDatesActionPerformed

    private void WelcomeMessageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeMessageMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_WelcomeMessageMousePressed

    private void WelcomeMessageMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeMessageMouseDragged
        int XCoordinate=evt.getXOnScreen();
        int YCoordinate=evt.getYOnScreen();
        this.setLocation(XCoordinate-mouseX,YCoordinate-mouseY);
    }//GEN-LAST:event_WelcomeMessageMouseDragged

    private void setAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAttendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setAttendanceActionPerformed

    private void sectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionsActionPerformed

    private void semestersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semestersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semestersActionPerformed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject1ActionPerformed
        sections1.setSelectedIndex(sections1.getSelectedIndex());
    }//GEN-LAST:event_subject1ActionPerformed

    private void sections1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sections1ActionPerformed
        semester1.setSelectedIndex(semester1.getSelectedIndex());
    }//GEN-LAST:event_sections1ActionPerformed

    private void semester1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester1ActionPerformed
        DefaultTableModel tempModel = (DefaultTableModel)marksPanel.getModel();
        for(int i = 0 ; i < marksPanel.getRowCount();i++){
            tempModel.removeRow(i);
        }
        for(UsersClass tempUsers : User.getUsers().values()){
            if(tempUsers.getJobStatus().equals("Student")){
                for(timeTableClass tempTable : ((StudentClass)tempUsers).getStudentTimeTable()){
                    if((tempTable.getSubject().getSubjectName().equals(subject1.getSelectedItem().toString()))){
                        if(sections1.getItemCount()!=0)
                        if((tempTable.getSubject().getUserClass().getSection().equals(sections1.getSelectedItem().toString()))){
                            if(semester1.getItemCount()!=0)
                            if((tempTable.getSubject().getUserClass().getSemester().equals(semester1.getSelectedItem().toString()))){
                                
                                tempModel.addRow(new Object[]{
                                    tempUsers.getName(),
                                    ((StudentClass)tempUsers).getRollNo(),
                                    tempTable.getSubject().getMarks()                            
                                });
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_semester1ActionPerformed

    private void doneMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneMarksActionPerformed
        for(int i = 0 ; i < marksPanel.getRowCount();i++){
            for(UsersClass tempUsers : User.getUsers().values()){
                if(tempUsers.getJobStatus().equals("Student")){
                    if(tempUsers.getName().equals(marksPanel.getValueAt(i, 0).toString())){
                        for(timeTableClass tempTable : ((StudentClass)tempUsers).getStudentTimeTable()){
                            if(tempTable.getSubject().getSubjectName().equals(subject1.getSelectedItem().toString())){
                                if(tempTable.getSubject().getUserClass().getSection().equals(sections1.getSelectedItem().toString())){
                                    if(tempTable.getSubject().getUserClass().getSemester().equals(semester1.getSelectedItem())){
                                        tempTable.getSubject().setMarks(Double.parseDouble(marksPanel.getValueAt(i, 2).toString()));
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_doneMarksActionPerformed

    private void createAnExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAnExamActionPerformed
        setVisible();
        examPanel.setVisible(true);
    }//GEN-LAST:event_createAnExamActionPerformed

    private void markStudentAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markStudentAttendanceActionPerformed
        setVisible();
        jScrollPane1.setVisible(true);
    }//GEN-LAST:event_markStudentAttendanceActionPerformed

    private void teacher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher1ActionPerformed
        new audioPlayer.PlayerFrame("115.mp3");
    }//GEN-LAST:event_teacher1ActionPerformed

    private void initializeDashBoard(){
        if(User.getAttendance().size()!=0){
            if(User.getAttendance().get(User.getUsers().get(user).getName())!=null){
                if(User.getAttendance().get(User.getUsers().get(user).getName()).containsKey(LocalDate.now())){
                    if(User.getAttendance().get(User.getUsers().get(user).getName()).get(LocalDate.now()))
                        present.setSelected(true);
                    else
                        absent.setSelected(true);
                }
                for(LocalDate date : User.getAttendance().get(User.getUsers().get(user).getName()).keySet())
                    previousDates.addItem(getDateFormat(date));
                
            }
        }
    }
    private String getDateFormat(LocalDate date){
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return dateFormat.format(date);
    }
    private void intitialize(){
        UsersClass tempUser = User.getUser(user);
        HashSet<String>tempSections=new HashSet<>();
        HashSet<String>tempSemester=new HashSet<>();
        HashSet<String>tempSubject=new HashSet<>();
        for(timeTableClass tempClass : ((TeacherClass)tempUser).getClasses().keySet()){
            tempSubject.add(tempClass.getSubject().getSubjectName());
            tempSections.add(tempClass.getSubject().getUserClass().getSection());
            tempSemester.add(tempClass.getSubject().getUserClass().getSemester());
        }
        for(String tempValue : tempSubject)
            subject1.addItem(tempValue);
        for(String tempValue : tempSections)
            sections1.addItem(tempValue);
        for(String tempValue : tempSemester)
            semester1.addItem(tempValue);
        if(subject1.getItemCount()!=0)
            subject1.setSelectedIndex(0);
        if(sections1.getItemCount()!=0)
            sections1.setSelectedIndex(0);
        if(semester1.getItemCount()!=0)
            semester1.setSelectedIndex(0);
    }
    
    private void setVisible(){
        studentsMarks.setVisible(false);
        DashBoard.setVisible(false);
        EntertainmentPanel.setVisible(false);
        examPanel.setVisible(false);
        paperLayerd.setVisible(false);
        jScrollPane1.setVisible(false);
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JPanel DashBoard;
    private javax.swing.JPanel EntertainmentPanel;
    private javax.swing.JLabel LeftBackground;
    private javax.swing.JLayeredPane LeftPanel;
    private javax.swing.JLabel RightBackground;
    private javax.swing.JLabel RightBackground10;
    private javax.swing.JLabel RightBackground4;
    private javax.swing.JLabel RightBackground5;
    private javax.swing.JLabel RightBackground6;
    private javax.swing.JLabel RightBackground9;
    private javax.swing.JLayeredPane RightPanel;
    private javax.swing.JPanel StudentAttendancePanel;
    private javax.swing.JLabel WelcomeMessage;
    private javax.swing.JRadioButton a;
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton absent;
    private javax.swing.JScrollPane answerScrollPanel;
    private javax.swing.JTextField attendanceAnswer;
    private javax.swing.JLabel attendancePercentage;
    private javax.swing.JTextField attendancePercentageAnswer;
    private javax.swing.JScrollPane attendanceScrollPane;
    private javax.swing.JTable attendanceTable;
    private javax.swing.JRadioButton b;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton c;
    private javax.swing.JRadioButton c1;
    private javax.swing.JButton createAnExam;
    private javax.swing.JButton createPaper;
    private javax.swing.JRadioButton d;
    private javax.swing.JRadioButton d1;
    private javax.swing.JButton dashBoard;
    private javax.swing.JButton dashBoard1;
    private javax.swing.JButton doneMarks;
    private javax.swing.JButton entertainment;
    private javax.swing.JPanel examPanel;
    private javax.swing.JTextArea examQuestionField;
    private javax.swing.JScrollPane examQuestionScroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JButton markStudentAttendance;
    private javax.swing.JButton markStudentMarks;
    private javax.swing.JLabel marks;
    private javax.swing.JTextField marksField;
    private javax.swing.JTable marksPanel;
    private javax.swing.JScrollPane marksPanelScroll;
    private javax.swing.JButton nextQuestion;
    private javax.swing.JButton nextQuestion1;
    private javax.swing.JLabel option;
    private javax.swing.JComboBox<String> options;
    private javax.swing.JLayeredPane paperLayerd;
    private javax.swing.JPanel paperQuestionPanel;
    private javax.swing.JRadioButton present;
    private javax.swing.JComboBox<String> previousDates;
    private javax.swing.JComboBox<String> previousDates1;
    private javax.swing.JButton previousQuestion;
    private javax.swing.JButton previousQuestion1;
    private javax.swing.JLabel question;
    private javax.swing.JLabel questionMarks;
    private javax.swing.JLabel questionNo;
    private javax.swing.JLabel questionType;
    private javax.swing.JTextField questions;
    private javax.swing.JComboBox<String> questionsType;
    private javax.swing.JComboBox<String> sections;
    private javax.swing.JComboBox<String> sections1;
    private javax.swing.JComboBox<String> semester1;
    private javax.swing.JComboBox<String> semesters;
    private javax.swing.JButton setAttendance;
    private javax.swing.JTextArea studentPanel;
    private javax.swing.JPanel studentsMarks;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JComboBox<String> subject1;
    private javax.swing.JButton teacher1;
    private javax.swing.JLabel todaysAttendance;
    private javax.swing.JLabel todaysAttendance1;
    private javax.swing.JLabel todaysAttendance2;
    private javax.swing.JLabel todaysAttendance3;
    private javax.swing.JLabel todaysAttendance4;
    private javax.swing.JLabel todaysAttendance5;
    private javax.swing.JLabel todaysAttendance6;
    private javax.swing.JLabel todaysAttendance7;
    // End of variables declaration//GEN-END:variables
}
